source 'https://rubygems.org'

gem 'thin'
gem 'sinatra'
gem 'twitter'
gem 'googlecharts'
gem 'chronic'
gem 'sqlite3'
gem 'binding_of_caller'
gem 'better_errors'
gem 'rake'
gem 'cucumber'
gem 'capybara'
gem 'rspec'
gem 'simplecov'
gem 'selenium-webdriver'
gem 'bcrypt'